In [1]:
import pandas as pd


In [2]:
messages=pd.read_csv(r"C:\Users\lenovo\Downloads\SMSSpamCollection.txt",sep="\t",names=["label","message"])

In [3]:
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
messages.shape

(5572, 2)

In [5]:
messages['message'].loc[10]

"I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today."

In [6]:
#data cleaning and preprocessing
import re 
import nltk
from nltk.tokenize import word_tokenize,sent_tokenize
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [8]:
corpus=[]
for i in range(0,len(messages)):
    filter=re.sub('[^a-zA-Z0-9]',' ',messages['message'][i])
    filter=filter.lower()
    filter=filter.split()
    
    filter=[ps.stem(word) for word in filter if word not in set(stopwords.words('english'))]
    filter=' '.join(filter)
    corpus.append(filter)

In [9]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl 3 week word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 week free mem

In [10]:
#creating BOW model

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,binary=True)
X=cv.fit_transform(corpus).toarray()

In [10]:
X[1]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [11]:
X.shape  #selecting top 2500 feature

(5572, 2500)

In [14]:
y=pd.get_dummies(messages['label'])
print(type(y))
y.head()
#y.columns

<class 'pandas.core.frame.DataFrame'>


ham   spam
0   True  False
1   True  False
2  False   True
3   True  False
4   True  False

In [20]:
y=y.iloc[:,1].values

In [21]:
#test train
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [22]:
from sklearn.naive_bayes import MultinomialNB
spam_detect=MultinomialNB().fit(X_train,y_train)

In [23]:
y_pred=spam_detect.predict(X_test)

In [24]:
y_pred

array([False, False, False, ..., False,  True, False])

In [25]:
from sklearn.metrics import accuracy_score,classification_report
score=(accuracy_score(y_test,y_pred))

In [26]:
score

0.9832535885167464

In [27]:
classification=classification_report(y_pred,y_test)

In [28]:
print(classification)

              precision    recall  f1-score   support

       False       0.99      0.99      0.99      1446
        True       0.94      0.93      0.94       226

    accuracy                           0.98      1672
   macro avg       0.97      0.96      0.96      1672
weighted avg       0.98      0.98      0.98      1672



#Create TF-IDF

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [30]:
tf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))

In [31]:
X1=tf.fit_transform(corpus).toarray()

In [32]:
#Train_test 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.3,random_state=42)

In [33]:
from sklearn.naive_bayes import MultinomialNB
spam_detect=MultinomialNB().fit(X_train,y_train)

In [34]:
y_pred=spam_detect.predict(X_test)

In [35]:
from sklearn.metrics import accuracy_score,classification_report
score=(accuracy_score(y_test,y_pred))

In [36]:
score

0.9826555023923444

In [37]:
classification=classification_report(y_pred,y_test)

In [38]:
print(classification)

              precision    recall  f1-score   support

       False       1.00      0.98      0.99      1475
        True       0.88      0.99      0.93       197

    accuracy                           0.98      1672
   macro avg       0.94      0.99      0.96      1672
weighted avg       0.98      0.98      0.98      1672



USE Desicision Tree

In [39]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
rf=RandomForestClassifier()

In [41]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [42]:
y_pred=rf.predict(X_test)

In [43]:
y_pred

array([False, False, False, ..., False,  True, False])

In [44]:
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

0.9844497607655502
              precision    recall  f1-score   support

       False       1.00      0.98      0.99      1474
        True       0.88      1.00      0.94       198

    accuracy                           0.98      1672
   macro avg       0.94      0.99      0.96      1672
weighted avg       0.99      0.98      0.98      1672



In [45]:
#pip install --upgrade pip

In [46]:
#pip install scipy

In [47]:
#pip install -U gensim

In [48]:
from nltk.stem import WordNetLemmatizer
lemmatize=WordNetLemmatizer()

In [49]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, messages['message']) if i<1]
#you will see that around 8 sentences are turned into blanks and their length is zero. The reason they turn blank is 
#that all the words in the sentences below are in stopwords list.

[[0, '', 'What you doing?how are you?'],
 [0, '', 'Where @'],
 [0, '', 'Can a not?'],
 [0, '', ':) '],
 [0, '', 'What you doing?how are you?'],
 [0, '', ':( but your not here....'],
 [0, '', ':-) :-)']]

In [50]:
corpus=[]
for i in range(0,len(messages)):
    filter=re.sub('[^a-zA-Z0-9]',' ',messages['message'][i])
    filter=filter.lower()
    filter=filter.split()
    
    filter=[lemmatize.lemmatize(word) for word in filter if word not in set(stopwords.words('english'))]
    filter=' '.join(filter)
    corpus.append(filter)


In [51]:
corpus[800]

'gimme lt gt minute ago'

In [52]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
#Simple process:->Convert a document into a list of lowercase tokens, ignoring tokens that are too short or too long.

In [53]:
corpus[405]

'yep great loxahatchee xmas tree burning lt gt start hour'

In [54]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))



In [55]:
words[0]

['go',
 'jurong',
 'point',
 'crazy',
 'available',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amore',
 'wat']

In [56]:
import gensim

In [57]:
from gensim.models import Word2Vec
model = Word2Vec(words, window=6, min_count=2)
#min_count=Ignores all words with total frequency lower than this.

In [58]:
(model.wv.index_to_key)

['call',
 'get',
 'ur',
 'gt',
 'go',
 'lt',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'good',
 'time',
 'got',
 'text',
 'love',
 'want',
 'send',
 'need',
 'one',
 'txt',
 'today',
 'going',
 'stop',
 'home',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'please',
 'pls',
 'co',
 'msg',
 'make',
 'dear',
 'night',
 'message',
 'well',
 'say',
 'min',
 'thing',
 'much',
 'great',
 'claim',
 'hope',
 'oh',
 'hey',
 'give',
 'number',
 'happy',
 'friend',
 'work',
 'wat',
 'way',
 'yes',
 'www',
 'let',
 'prize',
 'right',
 'tomorrow',
 'already',
 'ask',
 'said',
 'win',
 'amp',
 'life',
 'cash',
 'yeah',
 'im',
 'tone',
 'really',
 'babe',
 'meet',
 'find',
 'miss',
 'morning',
 'uk',
 'last',
 'service',
 'thanks',
 'care',
 'com',
 'would',
 'anything',
 'year',
 'also',
 'lol',
 'nokia',
 'every',
 'feel',
 'keep',
 'sure',
 'pick',
 'urgent',
 'contact',
 'sent',


In [59]:
model.corpus_count

5565

In [60]:
model.corpus_total_words

47642

In [61]:
model.epochs

5

In [62]:
model.wv.similar_by_word('last')

[('one', 0.999802827835083),
 ('today', 0.9997761249542236),
 ('keep', 0.999774694442749),
 ('get', 0.9997661113739014),
 ('like', 0.999765932559967),
 ('ur', 0.9997606873512268),
 ('know', 0.9997563362121582),
 ('dont', 0.9997466206550598),
 ('go', 0.9997451305389404),
 ('day', 0.9997434020042419)]

<h1>AVERAGE WORD2Vec</h1>
Avg Word2Vec is an extension of the Word2Vec model that generates vector representations for sentences or documents instead of individual words. It works by taking the average of the vector representations of all the words in a sentence or document to generate a single vector representation for the entire text

In [63]:
import numpy as np
def avg_word2vec(doc):
    #remove out-of-vocalbulary words
    #sent=[word for word in doc if not in model.wv.inex_to_key]
    #print(sent)

    return np.mean([model.wv[word] for word in doc if word  in model.wv.index_to_key],axis=0)

In [64]:
#pip install tqdm

Note: you may need to restart the kernel to use updated packages.


In [66]:
from tqdm import tqdm

In [67]:
words[66]

['today',
 'song',
 'dedicated',
 'day',
 'song',
 'dedicate',
 'send',
 'ur',
 'valuable',
 'frnds',
 'first',
 'rply']

In [68]:
type(model.wv.index_to_key)

list

In [69]:
#apply for entire sentences
x=[]
for i in tqdm(range(len(words))):
    x.append(avg_word2vec(words[i]))
    

  0%|                                                                                         | 0/5565 [00:00<?, ?it/s]C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|███████████████████████████████████████████████████████████████████████████| 5565/5565 [00:00<00:00, 13162.08it/s]


In [70]:
type(x)

list

In [71]:
len(x)

5565

In [72]:
x

[array([-0.08577303,  0.31691003,  0.05609877, -0.00710706, -0.0203454 ,
        -0.39066517,  0.08491825,  0.55506206, -0.17782305, -0.1401544 ,
        -0.10366488, -0.37583098, -0.03481244,  0.05843871,  0.06995612,
        -0.24372798, -0.01208922, -0.37542167, -0.08022738, -0.4429717 ,
         0.19264   ,  0.06807161,  0.14726777, -0.08483944, -0.15818986,
         0.07245408, -0.24953969, -0.28865996, -0.25961187,  0.08877873,
         0.31831607,  0.02287742,  0.12927233, -0.14056824, -0.12118757,
         0.2387237 , -0.0462194 , -0.29562554, -0.1774149 , -0.5513373 ,
         0.01519283, -0.29867777, -0.03174428,  0.05150564,  0.25562963,
        -0.16174625, -0.22415717, -0.02565134,  0.10559883,  0.1762191 ,
         0.1378783 , -0.18677522, -0.07367622, -0.09068368, -0.16166806,
         0.10870486,  0.14227071,  0.00529107, -0.31430852, -0.07636809,
         0.04283366,  0.1191147 , -0.14351945,  0.00074395, -0.33898437,
         0.30737424,  0.11699937,  0.26690182, -0.3

In [73]:
X_new=x

In [74]:
X_new

[array([-0.08577303,  0.31691003,  0.05609877, -0.00710706, -0.0203454 ,
        -0.39066517,  0.08491825,  0.55506206, -0.17782305, -0.1401544 ,
        -0.10366488, -0.37583098, -0.03481244,  0.05843871,  0.06995612,
        -0.24372798, -0.01208922, -0.37542167, -0.08022738, -0.4429717 ,
         0.19264   ,  0.06807161,  0.14726777, -0.08483944, -0.15818986,
         0.07245408, -0.24953969, -0.28865996, -0.25961187,  0.08877873,
         0.31831607,  0.02287742,  0.12927233, -0.14056824, -0.12118757,
         0.2387237 , -0.0462194 , -0.29562554, -0.1774149 , -0.5513373 ,
         0.01519283, -0.29867777, -0.03174428,  0.05150564,  0.25562963,
        -0.16174625, -0.22415717, -0.02565134,  0.10559883,  0.1762191 ,
         0.1378783 , -0.18677522, -0.07367622, -0.09068368, -0.16166806,
         0.10870486,  0.14227071,  0.00529107, -0.31430852, -0.07636809,
         0.04283366,  0.1191147 , -0.14351945,  0.00074395, -0.33898437,
         0.30737424,  0.11699937,  0.26690182, -0.3

In [69]:
words[0]

['go',
 'jurong',
 'point',
 'crazy',
 'available',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amore',
 'wat']

In [75]:
X_new[0].shape   #1st sentences having 100 dimensions

(100,)

In [76]:
y = messages[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].values
len(y)

5565

In [77]:
#final independent feature 
#we have to reshape the X as vectors will be in the row....i.e i row and 100 columns
print(x[0].shape)   #one-dimensional
print(x[0].reshape(1,-1).shape)   #1 row and 100 columns i.e 1st sentences in row and  with 100 diff vectors

(100,)
(1, 100)


In [78]:
dfs = [pd.DataFrame(X_new[i].reshape(1, -1)) for i in range(len(x))]
df = pd.concat(dfs, ignore_index=True)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_9692\2962949495.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(dfs, ignore_index=True)


In [79]:
df.head()

0         1         2         3         4         5         6   \
0 -0.085773  0.316910  0.056099 -0.007107 -0.020345 -0.390665  0.084918   
1 -0.054232  0.209467  0.036793 -0.006995 -0.013680 -0.257096  0.055357   
2 -0.083683  0.292903  0.054286 -0.003788 -0.016227 -0.359707  0.078248   
3 -0.102175  0.388188  0.069516 -0.006926 -0.028020 -0.480349  0.106617   
4 -0.100050  0.372537  0.065628 -0.005676 -0.024293 -0.462518  0.105291   

         7         8         9   ...        90        91        92        93  \
0  0.555062 -0.177823 -0.140154  ...  0.391433  0.143488 -0.018125  0.135515   
1  0.369908 -0.117715 -0.095923  ...  0.260677  0.097417 -0.013711  0.086325   
2  0.506497 -0.165657 -0.123534  ...  0.360030  0.128554 -0.019554  0.118472   
3  0.686385 -0.225467 -0.165970  ...  0.483649  0.179136 -0.020880  0.171509   
4  0.654689 -0.212030 -0.156443  ...  0.464207  0.176770 -0.016907  0.161411   

         94        95        96        97        98        99  
0  0.441141  0.260526  0.202036 -0.240217  0.077813 -0.052791  
1  0.300062  0.176528  0.140685 -0.160754  0.051963 -0.034563  
2  0.406997  0.248652  0.182294 -0.215543  0.071460 -0.045538  
3  0.552849  0.321835  0.254896 -0.296180  0.095461 -0.076440  
4  0.524826  0.313615  0.242741 -0.280209  0.098695 -0.062959  

[5 rows x 100 columns]

In [128]:
#independent feature
X2=df


In [81]:
y

array([ True,  True, False, ...,  True,  True,  True])

In [93]:
#convert y to numerical variable
y=y.astype('int')

In [94]:
df['Output']=y

In [95]:
df.head()

0         1         2         3         4         5         6  \
0 -0.085773  0.316910  0.056099 -0.007107 -0.020345 -0.390665  0.084918   
1 -0.054232  0.209467  0.036793 -0.006995 -0.013680 -0.257096  0.055357   
2 -0.083683  0.292903  0.054286 -0.003788 -0.016227 -0.359707  0.078248   
3 -0.102175  0.388188  0.069516 -0.006926 -0.028020 -0.480349  0.106617   
4 -0.100050  0.372537  0.065628 -0.005676 -0.024293 -0.462518  0.105291   

          7         8         9  ...        91        92        93        94  \
0  0.555062 -0.177823 -0.140154  ...  0.143488 -0.018125  0.135515  0.441141   
1  0.369908 -0.117715 -0.095923  ...  0.097417 -0.013711  0.086325  0.300062   
2  0.506497 -0.165657 -0.123534  ...  0.128554 -0.019554  0.118472  0.406997   
3  0.686385 -0.225467 -0.165970  ...  0.179136 -0.020880  0.171509  0.552849   
4  0.654689 -0.212030 -0.156443  ...  0.176770 -0.016907  0.161411  0.524826   

         95        96        97        98        99  Output  
0  0.260526  0.202036 -0.240217  0.077813 -0.052791       1  
1  0.176528  0.140685 -0.160754  0.051963 -0.034563       1  
2  0.248652  0.182294 -0.215543  0.071460 -0.045538       0  
3  0.321835  0.254896 -0.296180  0.095461 -0.076440       1  
4  0.313615  0.242741 -0.280209  0.098695 -0.062959       1  

[5 rows x 101 columns]

In [96]:
X2.dropna(inplace=True)

In [97]:
X2.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
Output    0
Length: 101, dtype: int64

In [98]:
y=df['Output']

In [112]:
X2=X2.drop('Output',axis=1)

In [113]:
#Train_test 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X2,y,test_size=0.2)

In [114]:
type(X_train)

pandas.core.frame.DataFrame

In [115]:
y_train

5098    1
3575    1
3674    1
3087    1
3169    1
       ..
3717    1
1541    1
3965    1
3597    1
365     1
Name: Output, Length: 4432, dtype: int32

In [116]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [117]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [120]:
y_pred=rf.predict(X_test)

In [121]:
from sklearn.metrics import accuracy_score,classification_report
accuracy=accuracy_score(y_test,y_pred)

In [123]:
accuracy

0.9567177637511272

In [125]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.77      0.84       162
           1       0.96      0.99      0.97       947

    accuracy                           0.96      1109
   macro avg       0.94      0.88      0.91      1109
weighted avg       0.96      0.96      0.96      1109

